### ISSUE TITLE
  local variable 'f' referenced before assignment in _http.py", line 109

### ISSUE THREAD

**Issue by Oi-apps** [python-mechanize/mechanize#35]
https://github.com/python-mechanize/mechanize/blob/master/mechani  
    line = f.readline()
    local variable 'f' referenced before assignment

Traceback (most recent call last):

    br.open('http://example.com/')
  File "<....>site-packages/mechanize/_mechanize.py", line 253, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "<....>site-packages/mechanize/_mechanize.py", line 283, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "<....>site-packages/mechanize/_opener.py", line 188, in open
    req = meth(req)
  File "<....>site-packages/mechanize/_http.py", line 176, in http_request
    self.rfp.read()
  File "<....>site-packages/mechanize/_http.py", line 109, in read
    line = f.readline()
UnboundLocalError: local variable 'f' referenced before assignment

**Comment by kovidgoyal** [comment]
dup of #34
