### ISSUE TITLE
File upload broken on python3

### ISSUE THREAD

**Issue by karottenbaum** [python-mechanize/mechanize#54]
On Python 3 (3.5.3) with Mechanize 0.4.5, file upload of an APK file fails with the following error: 
<details>
<summary>Error</summary>

```
Traceback (most recent call last):
  File "put_version.py", line 84, in <module>
    r=b.submit()
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_mechanize.py", line 684, in submit
    return self.open(self.click(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_mechanize.py", line 674, in click
    request = self.form.click(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_form_controls.py", line 2262, in click
    self._request_class)
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_form_controls.py", line 2480, in _click
    return control._click(self, coord, return_type, request_class)
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_form_controls.py", line 1520, in _click
    r = form._switch_click(return_type, request_class)
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_form_controls.py", line 2561, in _switch_click
    req_data = self._request_data()
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_form_controls.py", line 2544, in _request_data
    mw, encode_data(k), encode_data(v))
  File "/usr/local/lib/python3.5/dist-packages/mechanize/_form_controls.py", line 562, in _write_mime_data
    fh.write(file_object.read())
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 14-15: invalid continuation byte
```
</details>
I add the file to the request like this:

```
b.add_file(
    open(args.file),
    content_type='application/vnd.android.package-archive',
    name='apks', 
    filename=args.file.split('/')[-1])
# Await response
print("Uploading file...")
r=b.submit()
```

The script runs successfully on Python 2.7.13.
Seems like Mechanize is trying to decode a binary file, how to circumvent this?

**Comment by kovidgoyal** [comment]
Open the file in binary mode.
