### ISSUE TITLE
Tests fail on Python 3.10

### ISSUE THREAD

**Issue by swt2c** [python-mechanize/mechanize#64]
There's a few tests that are failing on Python 3.10 (3.10.0b2).  It looks like perhaps something changed with the `http.cookielib` library.

```
(env) [talbert@deasil mechanize]$ python3.10 run_tests.py 
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.............................EE/usr/lib64/python3.10/unittest/case.py:620: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmp0o2fcfq6' mode='w' encoding='UTF-8'>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
E/usr/lib64/python3.10/unittest/case.py:620: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmp5hhblmax' mode='w' encoding='UTF-8'>
  outcome.errors.clear()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
...............E.............................................<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
..<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
..<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
..<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
..<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
..........<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
........<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
..<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.....<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
.<frozen importlib._bootstrap>:914: ImportWarning: VendorImporter.find_spec() not found; falling back to find_module()
........................E........./usr/lib64/python3.10/collections/__init__.py:431: ResourceWarning: unclosed <socket.socket [closed] fd=8, family=AF_INET, type=SOCK_STREAM, proto=6>
  result = self._make(_map(kwds.pop, field_names, self))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib64/python3.10/collections/__init__.py:431: ResourceWarning: unclosed <socket.socket [closed] fd=9, family=AF_INET, type=SOCK_STREAM, proto=6>
  result = self._make(_map(kwds.pop, field_names, self))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
..../home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:85: ResourceWarning: unclosed <socket.socket [closed] fd=8, family=AF_INET, type=SOCK_STREAM, proto=6>
  for meth in dir(handler):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:85: ResourceWarning: unclosed <socket.socket [closed] fd=9, family=AF_INET, type=SOCK_STREAM, proto=6>
  for meth in dir(handler):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:85: ResourceWarning: unclosed <socket.socket [closed] fd=10, family=AF_INET, type=SOCK_STREAM, proto=6>
  for meth in dir(handler):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:85: ResourceWarning: unclosed <socket.socket [closed] fd=11, family=AF_INET, type=SOCK_STREAM, proto=6>
  for meth in dir(handler):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
............................................................................................................................./home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=10, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=13, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=16, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=17, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=18, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=11, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=20, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_opener.py:60: ResourceWarning: unclosed <socket.socket [closed] fd=21, family=AF_INET, type=SOCK_STREAM, proto=6>
  if not hasattr(handler, "add_parent"):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.....
======================================================================
ERROR: test_mozilla_cookiejar (test.test_cookies.CookieJarPersistenceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_cookies.py", line 1266, in test_mozilla_cookiejar
    new_c = save_and_restore(c, True)
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_cookies.py", line 1258, in save_and_restore
    new_c.load(ignore_discard=ignore_discard)
  File "/usr/lib64/python3.10/http/cookiejar.py", line 1807, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_clientcookie.py", line 199, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/tmp/tmpbvnor25x' does not look like a Netscape format cookies file

======================================================================
ERROR: test_mozilla_cookiejar_embedded_tab (test.test_cookies.CookieJarPersistenceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_cookies.py", line 1285, in test_mozilla_cookiejar_embedded_tab
    fh.write(MozillaCookieJar.header + "\n" +
AttributeError: type object 'MozillaCookieJar' has no attribute 'header'

======================================================================
ERROR: test_mozilla_cookiejar_initial_dot_violation (test.test_cookies.CookieJarPersistenceTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_cookies.py", line 1306, in test_mozilla_cookiejar_initial_dot_violation
    fh.write(MozillaCookieJar.header + "\n" +
AttributeError: type object 'MozillaCookieJar' has no attribute 'header'

======================================================================
ERROR: test_missing_name (test.test_cookies.CookieTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_cookies.py", line 342, in test_missing_name
    c.revert(ignore_expires=True, ignore_discard=True)
  File "/usr/lib64/python3.10/http/cookiejar.py", line 1827, in revert
    self.load(filename, ignore_discard, ignore_expires)
  File "/usr/lib64/python3.10/http/cookiejar.py", line 1807, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_clientcookie.py", line 199, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/tmp/tmp9zsagb2l' does not look like a Netscape format cookies file

======================================================================
ERROR: test_mozilla_cookiejar (test.test_functional.CookieJarTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_functional.py", line 684, in test_mozilla_cookiejar
    self._test_cookiejar(make_cookiejar, commit)
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_functional.py", line 664, in _test_cookiejar
    cookiejar = make_cookiejar()
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/test/test_functional.py", line 676, in make_cookiejar
    cj.revert()
  File "/usr/lib64/python3.10/http/cookiejar.py", line 1827, in revert
    self.load(filename, ignore_discard, ignore_expires)
  File "/usr/lib64/python3.10/http/cookiejar.py", line 1807, in load
    self._really_load(f, filename, ignore_discard, ignore_expires)
  File "/home/talbert/fedora-packaging/python-mechanize/mechanize/mechanize/_clientcookie.py", line 199, in _really_load
    raise LoadError(
http.cookiejar.LoadError: '/tmp/tmp-TempDirMaker-l7juwv4j/cookies.txt' does not look like a Netscape format cookies file

----------------------------------------------------------------------
Ran 305 tests in 6.048s

FAILED (errors=5)
```

**Comment by swt2c** [comment]
Thanks for the super fast fix!
