### ISSUE TITLE
ValueError raised on Browser.follow_link()

### ISSUE THREAD

**Issue by davidhaymond** [python-mechanize/mechanize#70]
Steps to reproduce on Python 3.10:

```python
import mechanize

br = mechanize.Browser()
br.open('https://informeddelivery.usps.com')
response = br.follow_link(text="Sign In")        # ValueError raised here
print(br.title())
print(response.geturl())
```

Traceback:

```
Traceback (most recent call last):
  File "/home/david/code/personal/mechanize/tester.py", line 4, in <module>
    res = br.follow_link(text="Sign In")
  File "/home/david/code/personal/mechanize/.venv/lib64/python3.10/site-packages/mechanize/_mechanize.py", line 725, in follow_link
    return self.open(self.click_link(link, **kwds))
  File "/home/david/code/personal/mechanize/.venv/lib64/python3.10/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/home/david/code/personal/mechanize/.venv/lib64/python3.10/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/home/david/code/personal/mechanize/.venv/lib64/python3.10/site-packages/mechanize/_opener.py", line 188, in open
    req = meth(req)
  File "/home/david/code/personal/mechanize/.venv/lib64/python3.10/site-packages/mechanize/_http.py", line 173, in http_request
    self.rfp.read()
  File "/home/david/code/personal/mechanize/.venv/lib64/python3.10/site-packages/mechanize/_http.py", line 106, in read
    line = f.readline()
  File "/home/david/code/personal/mechanize/.venv/lib64/python3.10/site-packages/mechanize/_response.py", line 224, in readline
    data = self.wrapped.readline()
ValueError: I/O operation on closed file.
```

**Comment by kovidgoyal** [comment]
That's caused by an inifnite redirect loop in the server when getting robots.txt. Use br.set_handle_robots(False) and you will be fine.
