### ISSUE TITLE
Response being sent but mechanize hanging

### ISSUE THREAD

**Issue by alper** [python-mechanize/mechanize#77]
I turned on all debugging and I can see that a response has been sent but mechanize is hanging for me and won't allow me to print it or get at it in another way.

Code:
```
import logging
import mechanize
import sys

logger = logging.getLogger("mechanize")
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.setLevel(logging.DEBUG)

browser = mechanize.Browser()

browser.set_debug_http(True)
browser.set_debug_responses(True)
browser.set_debug_redirects(True)

browser.set_handle_robots(False)
browser.set_handle_equiv(True)
browser.set_handle_gzip(True)
browser.set_handle_redirect(True)
browser.set_handle_referer(True)

browser.addheaders = [
    (
        "User-Agent",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15",
    ),
    ("Accept-Language", "en-GB,en;q=0.9"),
    ("Accept-Encoding", "gzip, deflate, br"),
    ("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"),
    ("Connection", "keep-alive"),
]
# resp = browser.open("https://www.python.org")
response = browser.open("https://www.handelsregister.de", timeout=10)

response2 = browser.follow_link(text="Advanced search")

open("output.html", "w").write(response2.read())
```

Stack trace if I kill the hung process:

```
^CTraceback (most recent call last):
  File "handelsregister.py", line 32, in <module>
    response = browser.open("https://www.handelsregister.de", timeout=10)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_opener.py", line 204, in open
    response = meth(req, response)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_urllib2_fork.py", line 536, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_opener.py", line 222, in error
    result = self._call_chain(*args)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_urllib2_fork.py", line 414, in _call_chain
    result = func(*args)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_urllib2_fork.py", line 655, in http_error_302
    return self.parent.open(new)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_mechanize.py", line 287, in _mech_open
    response = UserAgentBase.open(self, request, data)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_opener.py", line 204, in open
    response = meth(req, response)
  File "/Users/alper/.local/share/virtualenvs/handels-_d-0W85O/lib/python3.7/site-packages/mechanize/_http.py", line 304, in http_response
    self._sleep(pause)
KeyboardInterrupt
```

**Comment by kovidgoyal** [comment]
Look at the HTML the server is sending, it has

<meta http-equiv="refresh" content="1200;url=/rp_web/welcome.xhtml" />

turn off refresh handling and you should be fine.
