### ISSUE TITLE
Documentation/Code mismatch for "HTTPResponse"

### ISSUE THREAD

**Issue by barryrowlingson** [python-mechanize/mechanize#83]
Documentation for the open method of a browser:

https://mechanize.readthedocs.io/en/latest/browser_api.html#mechanize.Browser.open

says: "Returns: | A mechanize.Response object" but code seems to return a `response_seek_wrapper` object:

```
>>> br = mechanize.Browser()
>>> br.set_handle_robots(False)
>>> r = br.open("http://www.google.com/")
>>> r
<response_seek_wrapper at 0x7f09b1fbec80 whose wrapped object = <closeable_response at 0x7f09b1fbf100 whose fp = <_io.BufferedReader name=3>>>
```

Methods described in "The Response" section of docs:

https://mechanize.readthedocs.io/en/latest/browser_api.html#the-response

don't all work:

```
>>> r.geturl()
'http://www.google.com/'
>>> r.get_all_header_names()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/apps/thonny/lib/python3.10/site-packages/mechanize/_response.py", line 403, in get_all_header_names
    for line in self._headers.headers:
AttributeError: 'HTTPMessage' object has no attribute 'headers'. Did you mean: '_headers'?
```

And the class for HTTPResponse: "https://mechanize.readthedocs.io/en/latest/browser_api.html#mechanize._mechanize.HTTPResponse" doesn't seem to exist in the source code.

At which point I wonder about whether I'm doing the right thing or if there's some issues in the code. What I'm trying to do is see the response headers at this point.

This is using :

```
>>> mechanize.__version__
(0, 4, 8, None, None)
```

and in a venv with:

```
$ python -m pip freeze
html5lib==1.1
mechanize==0.4.8
six==1.16.0
webencodings==0.5.1
```

**Comment by kovidgoyal** [comment]
You do r.info() which gives you an HTTPMessage object from the stdlib
see the docs for HTTPMessage

**Comment by barryrowlingson** [comment]
That lets me get the headers, thanks, but I'm not sure this explains the errors and code/doc mismatches I'm seeing with your response object:

https://mechanize.readthedocs.io/en/latest/browser_api.html#the-response says:

Response objects in mechanize are seek() able file-like objects that support some additional methods, depending on the protocol used for the connection. The documentation below is for HTTP(s) responses, as these are the most common.

and details "get_all_header_values(name, normalize=True)" which doesn't exist when I get a response `r` as in my code above.

Have you removed these methods from the code but not the documentation?
